### PR TITLE
Implement project bulk upload from file to DB

### PR DESCRIPTION
**Pull request by McSlither**

### CODE REVIEW

**Comment by McSlither** [comment]
I think we should change the projects table id to "uuid DEFAULT uuid_generate_v4 ()" instead of generating that in client and also make it more usable for the bulk upload.

**Comment by McSlither** [comment]
Next step is to use csv header to set the columns we want to use when copying to DB.

**Review by ethdumplingz — COMMENTED** [review]
So, with this setup, the uploader needs to include all columns within the sheet right? and in the exact order.   Since this is an admin only feature (for now) I wonder if we can provide a template via google sheets.

**Comment by ethdumplingz** [comment]
Also, I don't have a problem with generating the project ID on the server.

**Comment by McSlither** [comment]
Changing column data type is kinda tricky with all the views referring to it, I don't want to change it without testing in separate DB.

As for a template, we can add an export functionality (and part of that give an option to export header only).

**Comment by McSlither** [comment]
Upload now uses the csv header so we don't need to include all columns

**Review by ethdumplingz — APPROVED** [review]

**Pull request merged**
